# Generated by Django 4.2.11 on 2025-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.CharField(default='To day', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='update_at',
            field=models.CharField(default='To day', max_length=254),
        ),
    ]
