# Generated by Django 5.2.4 on 2025-07-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
